// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzio58kzxgk1BBa6Dww5br2bfaqaq0bBk',
    appId: '1:46783707780:web:4b6e5336bf0edd0e7520d1',
    messagingSenderId: '46783707780',
    projectId: 'kargo-app-55246',
    authDomain: 'kargo-app-55246.firebaseapp.com',
    storageBucket: 'kargo-app-55246.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhzVX2FKtsAva0P7zcCjONQF9zFn56A0',
    appId: '1:46783707780:android:ba60aa135b9d33847520d1',
    messagingSenderId: '46783707780',
    projectId: 'kargo-app-55246',
    storageBucket: 'kargo-app-55246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqrFsqC9S2LndFwejrvBay6XE1-eHsAes',
    appId: '1:46783707780:ios:3b6d6a2085a19cff7520d1',
    messagingSenderId: '46783707780',
    projectId: 'kargo-app-55246',
    storageBucket: 'kargo-app-55246.firebasestorage.app',
    iosBundleId: 'com.example.kargotakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqrFsqC9S2LndFwejrvBay6XE1-eHsAes',
    appId: '1:46783707780:ios:3b6d6a2085a19cff7520d1',
    messagingSenderId: '46783707780',
    projectId: 'kargo-app-55246',
    storageBucket: 'kargo-app-55246.firebasestorage.app',
    iosBundleId: 'com.example.kargotakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzio58kzxgk1BBa6Dww5br2bfaqaq0bBk',
    appId: '1:46783707780:web:5ecad8f79010b5f67520d1',
    messagingSenderId: '46783707780',
    projectId: 'kargo-app-55246',
    authDomain: 'kargo-app-55246.firebaseapp.com',
    storageBucket: 'kargo-app-55246.firebasestorage.app',
  );
}
